In [1]:
import pandas as pd
import numpy as np
import swifter

c:\Users\phku0\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df = pd.read_parquet('data/dataset_merged_cleaned.parquet')
df.rename(columns={'stock_tickers': 'ticker'}, inplace=True)

In [3]:
df.head()

,time_published,source,title_sentiment_finbert,summary_sentiment_finbert,title_sentiment_vader,summary_sentiment_vader,topic_announcements,topic_market_movements,topic_legal_actions,topic_investment_sentiment,...,NER_India,NER_Russia,NER_Canada,NER_UK,NER_Trump,NER_ElonMusk,NER_JoeBiden,NER_FED,NER_Ukraine,NER_Japan
newsID,,,,,,,,,,,,,,,,,,,,,
1,2022-03-01 00:02:02,CNBC,-0.631240,-0.619794,0.0000,0.0000,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
2,2022-03-01 00:15:56,CNBC,-0.999999,-1.000000,-0.4939,0.3818,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,2022-03-01 00:46:51,Money Control,0.000000,0.999998,0.0000,-0.5106,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
4,2022-03-01 02:23:00,Economic Times,-0.999998,-0.995447,0.1531,-0.2960,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
5,2022-03-01 02:30:56,South China Morning Post,-0.985850,-0.971956,-0.1027,-0.4215,False,False,False,False,...,False,True,False,False,False,False,False,False,True,True

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1904665 entries, 1 to 1904665
Data columns (total 28 columns):
 #   Column                      Dtype
---  ------                      -----
 0   time_published              datetime64[ns]
 1   source                      object
 2   title_sentiment_finbert     float64
 3   summary_sentiment_finbert   float64
 4   title_sentiment_vader       float64
 5   summary_sentiment_vader     float64
 6   topic_announcements         bool
 7   topic_market_movements      bool
 8   topic_legal_actions         bool
 9   topic_investment_sentiment  bool
 10  topic_earnings              bool
 11  topic_analyst_ratings       bool
 12  topic_macro_econ            bool
 13  topic_research_insights     bool
 14  ticker                      object
 15  sectors                     object
 16  NER_US                      bool
 17  NER_China                   bool
 18  NER_India                   bool
 19  NER_Russia                  bool
 20  NER_Canada                  bool
 21  NER_UK                      bool
 22  NER_Trump                   bool
 23  NER_ElonMusk                bool
 24  NER_JoeBiden                bool
 25  NER_FED                     bool
 26  NER_Ukraine                 bool
 27  NER_Japan                   bool
dtypes: bool(20), datetime64[ns](1), float64(4), object(3)
memory usage: 167.1+ MB

In [5]:
gics_sector_etfs = {
  "Energy": "VDE",  # Vanguard Energy ETF
  "Materials": "VAW",  # Vanguard Materials ETF
  "Industrials": "VIS",  # Vanguard Industrials ETF
  "Consumer Discretionary": "VCR",  # Vanguard Consumer Discretionary ETF
  "Consumer Staples": "VDC",  # Vanguard Consumer Staples ETF
  "Health Care": "VHT",  # Vanguard Health Care ETF
  "Financials": "VFH",  # Vanguard Financials ETF
  "Information Technology": "VGT",  # Vanguard Information Technology ETF
  "Communication Services": "VOX",  # Vanguard Communication Services ETF
  "Utilities": "VPU",  # Vanguard Utilities ETF
  "Real Estate": "VNQ"  # Vanguard Real Estate ETF
}

# Function to append sector ETF tickers to the ticker list
def append_sector_etf(row):
  sectors_list = row['sectors']
  tickers_list = row['ticker']
  
  updated_tickers = list(tickers_list) if isinstance(tickers_list, (list, np.ndarray)) else []

  if isinstance(sectors_list, (list, np.ndarray)):
    for sector in sectors_list:
      if sector in gics_sector_etfs:
        etf_ticker = gics_sector_etfs[sector]
        if etf_ticker not in updated_tickers:
          updated_tickers.append(etf_ticker)
      
  return updated_tickers

df['ticker'] = df.swifter.apply(append_sector_etf, axis=1)

Pandas Apply: 100%|██████████| 1904665/1904665 [00:13<00:00, 142373.18it/s]

In [6]:
print(df.shape)
df.head()

(1904665, 28)

,time_published,source,title_sentiment_finbert,summary_sentiment_finbert,title_sentiment_vader,summary_sentiment_vader,topic_announcements,topic_market_movements,topic_legal_actions,topic_investment_sentiment,...,NER_India,NER_Russia,NER_Canada,NER_UK,NER_Trump,NER_ElonMusk,NER_JoeBiden,NER_FED,NER_Ukraine,NER_Japan
newsID,,,,,,,,,,,,,,,,,,,,,
1,2022-03-01 00:02:02,CNBC,-0.631240,-0.619794,0.0000,0.0000,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
2,2022-03-01 00:15:56,CNBC,-0.999999,-1.000000,-0.4939,0.3818,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,2022-03-01 00:46:51,Money Control,0.000000,0.999998,0.0000,-0.5106,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
4,2022-03-01 02:23:00,Economic Times,-0.999998,-0.995447,0.1531,-0.2960,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
5,2022-03-01 02:30:56,South China Morning Post,-0.985850,-0.971956,-0.1027,-0.4215,False,False,False,False,...,False,True,False,False,False,False,False,False,True,True

In [7]:
# Explode the 'ticker' column to handle multiple 'ticker' per article
df_exploded = df.explode('ticker')

# Drop rows where 'sectors' might be NaN after exploding (if the original list was empty)
df_exploded = df_exploded.dropna(subset=['ticker'])

print(df_exploded.shape)
df_exploded.head()

(3585467, 28)

,time_published,source,title_sentiment_finbert,summary_sentiment_finbert,title_sentiment_vader,summary_sentiment_vader,topic_announcements,topic_market_movements,topic_legal_actions,topic_investment_sentiment,...,NER_India,NER_Russia,NER_Canada,NER_UK,NER_Trump,NER_ElonMusk,NER_JoeBiden,NER_FED,NER_Ukraine,NER_Japan
newsID,,,,,,,,,,,,,,,,,,,,,
1,2022-03-01 00:02:02,CNBC,-0.631240,-0.619794,0.0000,0.0000,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,2022-03-01 02:23:00,Economic Times,-0.999998,-0.995447,0.1531,-0.2960,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,2022-03-01 02:23:00,Economic Times,-0.999998,-0.995447,0.1531,-0.2960,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
5,2022-03-01 02:30:56,South China Morning Post,-0.985850,-0.971956,-0.1027,-0.4215,False,False,False,False,...,False,True,False,False,False,False,False,False,True,True
5,2022-03-01 02:30:56,South China Morning Post,-0.985850,-0.971956,-0.1027,-0.4215,False,False,False,False,...,False,True,False,False,False,False,False,False,True,True

In [8]:
# group data by hour and aggregate the columns

aggregation_dict = {
  'time_published': 'count',  # for counting the number of rows

  ### sentiment columns ###
  'title_sentiment_finbert': 'mean',
  'summary_sentiment_finbert': 'mean',
  'title_sentiment_vader': 'mean',
  'summary_sentiment_vader': 'mean',

  ### topic columns ###
  'topic_announcements': 'sum',
  'topic_market_movements': 'sum',
  'topic_legal_actions': 'sum',
  'topic_investment_sentiment': 'sum',
  'topic_earnings': 'sum',
  'topic_analyst_ratings': 'sum',
  'topic_macro_econ': 'sum',
  'topic_research_insights': 'sum',

  ### NER columns ###
  'NER_US': 'sum',
  'NER_China': 'sum',
  'NER_India': 'sum',
  'NER_Russia': 'sum',
  'NER_Canada': 'sum',
  'NER_UK': 'sum',
  'NER_Trump': 'sum',
  'NER_ElonMusk': 'sum',
  'NER_JoeBiden': 'sum',
  'NER_FED': 'sum',
  'NER_Ukraine': 'sum',
  'NER_Japan': 'sum',
}


# Group by hour (using time_published) and sectors
df_grouped = df_exploded.groupby([pd.Grouper(key='time_published', freq='h'), 'ticker']).agg(aggregation_dict)
df_grouped.rename(columns={'time_published': 'news_count'}, inplace=True)
df_grouped.reset_index(inplace=True)
df_grouped.rename(columns={'time_published': 'timestamp'}, inplace=True)

In [9]:
print(df_grouped.shape)
df_grouped.head()

(846295, 27)

,timestamp,ticker,news_count,title_sentiment_finbert,summary_sentiment_finbert,title_sentiment_vader,summary_sentiment_vader,topic_announcements,topic_market_movements,topic_legal_actions,...,NER_India,NER_Russia,NER_Canada,NER_UK,NER_Trump,NER_ElonMusk,NER_JoeBiden,NER_FED,NER_Ukraine,NER_Japan
0,2022-03-01 00:00:00,VDE,1,-0.631240,-0.619794,0.00000,0.00000,0,0,0,...,0,1,0,0,0,0,0,0,1,0
1,2022-03-01 02:00:00,VAW,2,-0.492925,0.013697,-0.24225,0.09545,0,0,0,...,0,1,0,0,0,0,0,0,2,1
2,2022-03-01 02:00:00,VDE,2,-0.992924,-0.983702,0.02520,-0.35875,0,0,0,...,1,1,0,0,0,0,0,0,1,1
3,2022-03-01 02:00:00,VFH,1,-0.985850,-0.971956,-0.10270,-0.42150,0,0,0,...,0,1,0,0,0,0,0,0,1,1
4,2022-03-01 02:00:00,VIS,1,-0.999998,-0.995447,0.15310,-0.29600,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [10]:
tickers_list = df_grouped['ticker'].unique()
tickers_list

array(['VDE', 'VAW', 'VFH', ..., 'FRAF', 'TCBC', 'WMPN'], dtype=object)

In [11]:
# Retrieve return of ticker at that timestamp

df_return = pd.read_parquet('../data_collection/data_warehouse/stock_return.parquet')
df_return.reset_index(inplace=True)
df_return = df_return[df_return['ticker'].isin(tickers_list)]
df_return = df_return[df_return['timestamp'] >= '2022-03-01']

df = pd.merge(df_grouped, df_return[['timestamp', 'ticker', 'return_forwarded']],
           on=['timestamp', 'ticker'],
           how='right')

print(df.shape)
df.head()

(17601669, 28)

,timestamp,ticker,news_count,title_sentiment_finbert,summary_sentiment_finbert,title_sentiment_vader,summary_sentiment_vader,topic_announcements,topic_market_movements,topic_legal_actions,...,NER_Russia,NER_Canada,NER_UK,NER_Trump,NER_ElonMusk,NER_JoeBiden,NER_FED,NER_Ukraine,NER_Japan,return_forwarded
0,2022-03-01 09:00:00,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004980
1,2022-03-01 10:00:00,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.001296
2,2022-03-01 11:00:00,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.010230
3,2022-03-01 12:00:00,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.001927
4,2022-03-01 13:00:00,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000189

In [12]:
df.to_parquet('data/dataset_features_return.parquet', index=False)